### ISSUE TITLE
Code to Run

### ISSUE THREAD

**Issue by mechgguy** [Infineon/hackathon#2]
'''
This example shows how we fetched the issues from the Infineon organisation on GitHub.
Feel free to modify this code and fetch the issues again depending on your preferences.
If you run into API limits you can talk to us, maybe we can fetch some data for you using our access tokens.
'''

from github import Github
from datetime import datetime, timedelta
import pandas as pd

def main():
    
    try:
        import secret
        github = Github(secret.access_token)
    except:
        github = Github()
    
    github_org = 'Infineon'
    ifx = github.get_organization(github_org)

    # Go through all open GitHub issues and put them in a Pandas Dataframe
    
    df = pd.DataFrame()

    for repo in ifx.get_repos():
        print(f'Working on repo {repo.name}...')
        issues = repo.get_issues(state='all') # state='all' -> we also take closed issues for training.

        for issue in issues:
            comments = issue.get_comments()
            concatenated_comment = ''
            for comment in comments:
                print(f'comment is {comment.body} and on {comment.created_at} and updated at {comment.updated_at}')
                concatenated_comment = concatenated_comment + comment.body + str(comment.created_at) + str(comment.updated_at) + '\n' 
            print (concatenated_comment)
            if issue.pull_request == None: issue_type = 'issue'
            else: issue_type = 'pull-request'
            issue_data = {
                'id': [str(issue.id)],
                'title': [str(issue.title)],
                'repo_name': [str(repo.name)],
                'pr': [issue_type],
                'state': [str(issue.state)],
                'created': [issue.created_at],
                'updated': [issue.updated_at],
                'body': [str(issue.body)],
                'user_login': [str(issue.user.login)],
                'url': [str(issue.url)],
                'comments': [issue.comments],
                'user_type': [str(issue.user.type)],
                'labels': [[str(x) for x in issue.labels]],
                'assignees': [[str(x) for x in issue.assignees]],
                # added attributes
                'closed': [issue.closed_at],
                'alr':[str(issue.active_lock_reason)],
                'etag':[str(issue.etag)],
                'comment':concatenated_comment
                # 'comments_url':[str(issue.comments_url)]
                # 'an':[str(issue.)]
            }
            
            df = pd.concat([
                df, 
                pd.DataFrame(issue_data)
                ], ignore_index=True)
            print(df)
            break
        # For testing: End loop after first few issues
        if not df.empty: break

    # Make the issue ID the Dataframe index
    df.set_index('id', inplace=True)

    # Write Dataframe to Pickle file
    print('Saving dataframe:')
    print(df)
    df.to_pickle('github_issues_new.pkl')

    # Test readback from Pickle file
    print('Loading dataframe:')
    df = pd.read_pickle('github_issues_new.pkl')
    print(df)

if __name__ == '__main__':
    main()

**Comment by ederjc** [comment]
I ran the code with a limitation of about 300 issues and the result is saved [here](https://github.com/Infineon/hackathon/blob/master/examples/custom_pkl/github_issues_team10.pkl).

**Comment by mechgguy** [comment]
'''
This example shows how we fetched the issues from the Infineon organisation on GitHub.
Feel free to modify this code and fetch the issues again depending on your preferences.
If you run into API limits you can talk to us, maybe we can fetch some data for you using our access tokens.
'''

from github import Github
from datetime import datetime, timedelta
import pandas as pd

def main():
    
    try:
        import secret
        github = Github(secret.access_token)
    except:
        github = Github()
    
    github_org = 'Infineon'
    ifx = github.get_organization(github_org)

    # Go through all open GitHub issues and put them in a Pandas Dataframe
    
    df = pd.DataFrame()

    for repo in ifx.get_repos():
        print(f'Working on repo {repo.name}...')
        issues = repo.get_issues(state='all') # state='all' -> we also take closed issues for training.

        for issue in issues:
            comments = issue.get_comments()
            concatenated_comment = ''
            for comment in comments:
               
                concatenated_comment = concatenated_comment + f'comment is {comment.body} and on {comment.created_at} and updated at {comment.updated_at} by user {comment.user}. \n'
                # concatenated_comment = concatenated_comment + comment.body + str(comment.created_at) + str(comment.updated_at) + '\n' 
            # print (concatenated_comment)
            if issue.pull_request == None: issue_type = 'issue'
            else: issue_type = 'pull-request'
            issue_data = {
                'id': [str(issue.id)],
                'title': [str(issue.title)],
                'repo_name': [str(repo.name)],
                'pr': [issue_type],
                'state': [str(issue.state)],
                'created': [issue.created_at],
                'updated': [issue.updated_at],
                'body': [str(issue.body)],
                'user_login': [str(issue.user.login)],
                'url': [str(issue.url)],
                'comments': [issue.comments],
                'user_type': [str(issue.user.type)],
                'labels': [[str(x) for x in issue.labels]],
                'assignees': [[str(x) for x in issue.assignees]],
                # added attributes
                'closed': [issue.closed_at],
                'alr':[str(issue.active_lock_reason)],
                'etag':[str(issue.etag)],
                'comment':[concatenated_comment],
                # 'comments_url':[str(issue.comments_url)]
                'closedby':[str(issue.closed_by)],
                'labels':[str(issue.labels)]
            }
            
            df = pd.concat([
                df, 
                pd.DataFrame(issue_data)
                ], ignore_index=True)
            print(df)
            # break
        # For testing: End loop after first few issues
        if not df.empty: break

    # Make the issue ID the Dataframe index
    df.set_index('id', inplace=True)

    # Write Dataframe to Pickle file
    print('Saving dataframe:')
    print(df)
    df.to_pickle('github_issues_test.pkl')

    # Test readback from Pickle file
    print('Loading dataframe:')
    df = pd.read_pickle('github_issues_test.pkl')
    df.to_csv('github_issues_test.csv')
    print(df.describe)

if __name__ == '__main__':
    main()

**Comment by ederjc** [comment]
Had to fix a few things to make it run properly with open issues also.
Additionally I added a statement to read out weather the user is a member of Infineon organisation. This might also help.

Here the current version: https://github.com/Infineon/hackathon/blob/team10/examples/fetch_github_issues.py 
And the output of a ~300 issue run: https://github.com/Infineon/hackathon/blob/team10/examples/custom_pkl/github_issues_team10.pkl

**Comment by ederjc** [comment]
The full run is still ongoing, currently at issue #2695. I will upload the results in the morning.

**Comment by ederjc** [comment]
File is now there: https://github.com/Infineon/hackathon/blob/master/examples/custom_pkl/github_issues_with_comments.pkl @mechgguy

**Comment by mechgguy** [comment]
Thank You very much !!
