### ISSUE TITLE
Is this a Ranged Doppler?

### ISSUE THREAD

**Issue by callmesora** [Infineon/hackathon#6]
**Have you looked for an answer?**

We appreciate you checking the documentation, release notes, or the Developer community before asking. Please tell us where you looked, so we can fill the gap and help the next person too.

**Question/Issue**:

What can we help you with?
On the Infeneon DAQ Recorder, the data recorded is shown on a preview.
**Is this preview a Ranged Doppler or a Heatmap?**

![image](https://user-images.githubusercontent.com/61661948/170259383-34f1e281-d767-4096-954c-60055e37be93.png)

**Comment by souvikhazra** [comment]
Hello @callmesora , This is indeed a Range Doppler Map.
